AWSTemplateFormatVersion: 2010-09-09
Description: Detectify screenshot service DynamoDB stack

Parameters:
  Service:
    Type: String

Resources:
  DetectifyScreenshotServiceDB:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Sub ${Service}
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  StreamName:
    Description: Output the streams name
    Value:
      Fn::GetAtt: [ DetectifyScreenshotServiceDB , StreamArn ]
    Export:
      Name: ScreenshotStreamARN
